version: '3.7'
services:

  # Node.js application service
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  # MongoDB database service
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  # MongoDB Express (web-based UI) service  
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo-data:

